apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-simple
        image: registry.digitalocean.com/jenkins-test-repository/nginx-simple:latest
        ports:
        - containerPort: 80
